name: reusable
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Reusable Echo
    runs-on: ubuntu-latest
    steps:
      - run: echo this is a statement